language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer update --dev
  - phpenv config-add build/travis/phpenv/memcached.ini
  - phpenv config-add build/travis/phpenv/apc.ini
  - phpenv config-add build/travis/phpenv/redis.ini

script:
  - phpunit -v
