language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - memcached # will start memcached
  - redis

before_script:
  - composer update --dev
  - phpenv config-add build/travis/phpenv/memcached.ini
  - echo "no" | pecl install apcu-beta

script:
  - phpunit
